name: GitHub-Profile-Summary-Cards

on:
  create:
  push:
  schedule: # execute 04:14JST. cron is UTC
    - cron: "14 19 * * *"
  workflow_dispatch:

jobs:
  github-profile-summary-cards:
    runs-on: ubuntu-latest
    name: generate
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARDS_TOKEN }}
          UTC_OFFSET: 9
        with:
          USERNAME: ${{ github.repository_owner }}

  lapras-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: "yakumo"
